[package]
name = "pathtracer"
version = "0.1.0"
authors = ["Arian van Putten <aeroboy94@gmail.com>", "Reinier Remco Maas <reiniermaas@hotmail.com>"]

[dependencies]
sdl2 = "*"
cgmath = "*"
rand = "*"
memmap = "*"
itertools = "*"